### ISSUE TITLE
I get the error message when I run the sample command

### ISSUE THREAD

**Issue by chengyi-chris** [CCCjiang/CTRL#1]
python main_train.py --dataset cifar10 --mode normal --method simclr --threat_model our --channel 1 2 --trigger_position 15 31 --poison_ratio 0.01 --lr 0.06 --wd 0.0005 --magnitude 100.0 --poisoning --epochs 800 --gpu 0 --window_size 32 --trial clean

`Use GPU: 0 for training 
=> creating cnn model 'resnet18'
CIFAR-variant Resnet is loaded
Files already downloaded and verified
Files already downloaded and verified`

`File "/workspace/ChengYi/CTRL/loaders/diffaugment.py", line 266, in set_aug_diff
    raise NotImplementedError
NotImplementedError`

How do I solve this?

**Comment by meet-cjli** [comment]
Looks like I didn't place `raise NotImplementedError` in the `else` branch. I have updated the code. It should work now.
